Repository JGStudy/MoneyDefenseJGS, pull requests merged in 2025-05, with the labels that each got.

#94 Feature/92 거래내역 리스트 페이지 카테고리 드롭다운 수정
  MoneyDefenseJGS/src/api/transactionApi.js
  MoneyDefenseJGS/src/components/transaction/calendar/CategoryFilter.vue
  MoneyDefenseJGS/src/components/transaction/list/TransactionList.vue
  MoneyDefenseJGS/src/components/transaction/list/TransactionListItem.vue
  MoneyDefenseJGS/src/pages/transaction/TransactionPage.vue
  MoneyDefenseJGS/vite.config.js
Labels: 🎨 design, 🔁 refactor, ✨ feature

#98 Feature/96 설정 페이지 리팩토링
  MoneyDefenseJGS/src/components/setting/SideModal.vue
  MoneyDefenseJGS/src/pages/setting/SettingsPage.vue
  MoneyDefenseJGS/src/pages/setting/UserEditPage.vue
Labels: 🔁 refactor

#99 Feature/91 dbjson 변경에 맞춘 지출 시각화 페이지 수정
  MoneyDefenseJGS/package-lock.json
  MoneyDefenseJGS/package.json
  MoneyDefenseJGS/public/db/db.json
  MoneyDefenseJGS/src/components/report/MonthlyChart.vue
  MoneyDefenseJGS/src/components/report/TotalMoney.vue
  package-lock.json
Labels: 🔁 refactor

#102 Feature/93 오류팝업 최신버전
  MoneyDefenseJGS/src/api/transactionApi.js
  MoneyDefenseJGS/src/components/transaction/input/AmountInput.vue
  MoneyDefenseJGS/src/components/transaction/input/ConfirmModal.vue
  MoneyDefenseJGS/src/components/transaction/input/EditableTransactionInformation.vue
  MoneyDefenseJGS/src/pages/transaction/input/TransactionCreatePage.vue
  MoneyDefenseJGS/src/stores/transactionStore.js
Labels: 🎨 design, 🔁 refactor, 🐛 bugfix

#105 Feature/103 거래 리스트 카테고리 드롭다운 수정
  MoneyDefenseJGS/public/db/db.json
  MoneyDefenseJGS/src/components/common/MonthSelector.vue
  MoneyDefenseJGS/src/components/home/TransactionCard.vue
  MoneyDefenseJGS/src/components/layout/RealHeader.vue
  MoneyDefenseJGS/src/components/transaction/calendar/CategoryFilter.vue
  MoneyDefenseJGS/src/components/transaction/input/AmountInput.vue
Labels: 🔁 refactor, 🐛 bugfix

#111 Feature/109 홈 및 온보딩 페이지 쿠키 연결 리팩토링
  MoneyDefenseJGS/src/pages/home/HomePage.vue
  MoneyDefenseJGS/src/pages/onboarding/OnboardingPage.vue
  MoneyDefenseJGS/src/stores/userStore.js
Labels: 🔁 refactor

#113 Feature/110 회원가입 form 생성
  MoneyDefenseJGS/public/db/db.json
  MoneyDefenseJGS/src/api/userApi.js
  MoneyDefenseJGS/src/components/signup/SignupForm.vue
  MoneyDefenseJGS/src/pages/signup/SignupPage.vue
  MoneyDefenseJGS/src/router/index.js
Labels: ✨ feature

#120 Design: SingupPage.vue UI 수정
  MoneyDefenseJGS/src/pages/signup/SignupPage.vue
Labels: 🎨 design

#125 Feat/114 리포트 페이지 user id 연동 기능 수정 테일윈즈 변경
  MoneyDefenseJGS/src/api/reportApi.js
  MoneyDefenseJGS/src/components/report/CategoryChart.vue
  MoneyDefenseJGS/src/components/report/MonthlyChart.vue
  MoneyDefenseJGS/src/components/report/TotalMoney.vue
Labels: 🔁 refactor

#128 Feature/127 createtransaction 시 userid 1로 들어가는 에러 해결
  MoneyDefenseJGS/src/api/transactionApi.js
  MoneyDefenseJGS/src/pages/transaction/TransactionPage.vue
  MoneyDefenseJGS/src/pages/transaction/input/TransactionCreatePage.vue
  MoneyDefenseJGS/src/stores/transactionStore.js
Labels: 🔁 refactor, 🐛 bugfix

#133 Feature/132 거래내역 리스트 상세페이지
  MoneyDefenseJGS/src/api/transactionApi.js
  MoneyDefenseJGS/src/components/transaction/input/AmountInput.vue
  MoneyDefenseJGS/src/components/transaction/input/EditableTransactionInformation.vue
  MoneyDefenseJGS/src/components/transaction/list/TransactionList.vue
  MoneyDefenseJGS/src/components/transaction/list/TransactionListItem.vue
  MoneyDefenseJGS/src/pages/transaction/TransactionPage.vue
  MoneyDefenseJGS/src/pages/transaction/input/TransactionCreatePage.vue
  MoneyDefenseJGS/src/router/index.js
Labels: 🎨 design, 🔁 refactor, ✨ feature
