Repository JGStudy/MoneyDefenseJGS, pull requests merged in 2025-04, with the labels that each got.

#7 feature/6 시작 및 메인페이지 파일 생성
  MoneyDefenseJGS/src/components/Loading.vue
  MoneyDefenseJGS/src/components/RealHeader.vue
  MoneyDefenseJGS/src/components/UnderNavBar.vue
  MoneyDefenseJGS/src/pages/HomPage.vue
  MoneyDefenseJGS/src/pages/OnboardingPage.vue
Labels: documentation

#17 [#14] Feat: BaesButton 컴포넌트 생성
  MoneyDefenseJGS/src/components/common/BaseButton.vue
Labels: ✨ feature

#19 feature/15 공통 컴포넌트 header undernav 구현
  MoneyDefenseJGS/.gitignore
  MoneyDefenseJGS/index.html
  MoneyDefenseJGS/src/App.vue
  MoneyDefenseJGS/src/assets/icon/fonts/xeicon.eot
  MoneyDefenseJGS/src/assets/icon/fonts/xeicon.svg
  MoneyDefenseJGS/src/assets/icon/fonts/xeicon.ttf
  MoneyDefenseJGS/src/assets/icon/fonts/xeicon.woff
  MoneyDefenseJGS/src/assets/icon/fonts/xeicon.woff2
  MoneyDefenseJGS/src/assets/icon/xeicon.min.css
  MoneyDefenseJGS/src/components/common/BottomNavBar.vue
  MoneyDefenseJGS/src/components/common/RealHeader.vue
  MoneyDefenseJGS/src/main.js
Labels: 🎨 design, 📄 documentation, ✨ feature

#22 Feature/16 대시보드 페이지 생성
  MoneyDefenseJGS/db/Asset.json
  MoneyDefenseJGS/db/Dashboard.json
  MoneyDefenseJGS/db/MoneyBook.json
  MoneyDefenseJGS/db/Settings.json
  MoneyDefenseJGS/db/TransactionDetail.json
  MoneyDefenseJGS/src/components/DashBoard/CategoryChart.vue
  MoneyDefenseJGS/src/components/DashBoard/MonthlyChart.vue
  MoneyDefenseJGS/src/components/DashBoard/TotalMoney.vue
  MoneyDefenseJGS/src/pages/ReportPage.vue
  MoneyDefenseJGS/src/router/index.js
Labels: ✨ feature

#24 Feat: 공통 AppLayoutPage.vue 생성 및 App.vue 수정
  MoneyDefenseJGS/src/App.vue
  MoneyDefenseJGS/src/pages/layout/AppLayoutPage.vue
  MoneyDefenseJGS/src/router/index.js
Labels: 📄 documentation, ✨ feature

#28 Feature/5 거래 등록 페이지 구현
  MoneyDefenseJGS/src/components/EditableTransactionInformation.vue
  MoneyDefenseJGS/src/components/SaveTransactionButton.vue
  MoneyDefenseJGS/src/components/TransactionSummary.vue
  MoneyDefenseJGS/src/main.js
  MoneyDefenseJGS/src/pages/TransactionCreatePage.vue
  MoneyDefenseJGS/src/pages/stores/stores/transaction.ts
  MoneyDefenseJGS/src/router/index.js
  MoneyDefenseJGS/src/stores/transaction.ts
  MoneyDefenseJGS/src/stores/transactionStore.js
  MoneyDefenseJGS/vite.config.js
Labels: 🎨 design, ✨ feature

#30 Fix/파일 및 코드 정리
  MoneyDefenseJGS/src/App.vue
  MoneyDefenseJGS/src/components/button/ThemeToggle.vue
  MoneyDefenseJGS/src/components/common/RealHeader.vue
  MoneyDefenseJGS/src/components/setting/SettingListItem.vue
  MoneyDefenseJGS/src/components/setting/SideModal.vue
  MoneyDefenseJGS/src/components/setting/UserInfoCard.vue
  MoneyDefenseJGS/src/pages/report/ReportPage.vue
  MoneyDefenseJGS/src/pages/setting/SettingsPage.vue
  MoneyDefenseJGS/src/pages/setting/UserEditPage.vue
  MoneyDefenseJGS/src/router/index.js
Labels: 📄 documentation, 🐛 bugfix

#31 Feature/18 거래 내역 리스트 구현
  MoneyDefenseJGS/index.html
  MoneyDefenseJGS/public/db/Asset.json
  MoneyDefenseJGS/public/db/Dashboard.json
  MoneyDefenseJGS/public/db/MoneyBook.json
  MoneyDefenseJGS/public/db/Settings.json
  MoneyDefenseJGS/public/db/TransactionDetail.json
  MoneyDefenseJGS/src/components/transaction/CategoryFilter.vue
  MoneyDefenseJGS/src/components/transaction/TransactionList.vue
  MoneyDefenseJGS/src/components/transaction/TransactionListItem.vue
  MoneyDefenseJGS/src/pages/TransactionPage.vue
  MoneyDefenseJGS/src/router/index.js
Labels: 🎨 design, ✨ feature

#32 Feature/27 온보딩 페이지 레이아웃 구현
  MoneyDefenseJGS/src/assets/common.css
  MoneyDefenseJGS/src/components/common/BaseButton.vue
  MoneyDefenseJGS/src/main.js
  MoneyDefenseJGS/src/pages/start/OnboardingPage.vue
  MoneyDefenseJGS/src/router/index.js
Labels: 🎨 design, ✨ feature

#37 Feature/35 header 컴포넌트 기능 추가
  MoneyDefenseJGS/src/App.vue
  MoneyDefenseJGS/src/components/common/RealHeader.vue
  MoneyDefenseJGS/src/components/popup/ConfirmPopup.vue
  MoneyDefenseJGS/src/pages/layout/AppLayoutPage.vue
  MoneyDefenseJGS/src/pages/start/HomePage.vue
Labels: 🎨 design, 📄 documentation, 🔁 refactor, ✨ feature

#41 Feature/39 onboarding 페이지 기능 구현
  MoneyDefenseJGS/public/db/User.json
  MoneyDefenseJGS/src/api/userApi.js
  MoneyDefenseJGS/src/components/common/BaseButton.vue
  MoneyDefenseJGS/src/components/common/RealHeader.vue
  MoneyDefenseJGS/src/components/form/OnboardingForm.vue
  MoneyDefenseJGS/src/components/form/TextInputField.vue
  MoneyDefenseJGS/src/pages/start/OnboardingPage.vue
  MoneyDefenseJGS/src/stores/userStore.js
Labels: 🎨 design, 📄 documentation, ✨ feature

#42 Feature/23 리포트대시보드 페이지 구현
  MoneyDefenseJGS/package-lock.json
  MoneyDefenseJGS/package.json
  MoneyDefenseJGS/public/db/Dashboard.json
  MoneyDefenseJGS/src/components/DashBoard/CategoryChart.vue
  MoneyDefenseJGS/src/components/DashBoard/MonthlyChart.vue
  MoneyDefenseJGS/src/components/DashBoard/TotalMoney.vue
  MoneyDefenseJGS/src/pages/report/ReportPage.vue
Labels: ✨ feature

#44 Feature/29 거레 상세내역 페이지 구현
  MoneyDefenseJGS/src/components/EditTransaction.vue
  MoneyDefenseJGS/src/components/TransactionStore.vue
  MoneyDefenseJGS/src/components/TransactionTitle.vue
  MoneyDefenseJGS/src/pages/TransactionDetailPage.vue
  MoneyDefenseJGS/src/router/index.js
Labels: ✨ feature

#47 Feature/38 homepage 기능 구현
  MoneyDefenseJGS/public/db/Asset.json
  MoneyDefenseJGS/src/api/asset.js
  MoneyDefenseJGS/src/api/user.js
  MoneyDefenseJGS/src/components/common/BaseButton.vue
  MoneyDefenseJGS/src/components/common/BottomNavBar.vue
  MoneyDefenseJGS/src/components/form/OnboardingForm.vue
  MoneyDefenseJGS/src/components/form/TextInputField.vue
  MoneyDefenseJGS/src/pages/start/HomePage.vue
  MoneyDefenseJGS/src/pages/start/OnboardingPage.vue
  MoneyDefenseJGS/src/router/index.js
Labels: 🎨 design, ✨ feature, 🐛 bugfix

#48 Feature/43 대시보드 페이지 기능 구현
  MoneyDefenseJGS/package-lock.json
  MoneyDefenseJGS/package.json
  MoneyDefenseJGS/public/db/Dashboard.json
  MoneyDefenseJGS/src/api/report.js
  MoneyDefenseJGS/src/components/DashBoard/CategoryChart.vue
  MoneyDefenseJGS/src/components/DashBoard/MonthlyChart.vue
  MoneyDefenseJGS/src/components/DashBoard/TotalMoney.vue
  MoneyDefenseJGS/src/pages/report/ReportPage.vue
Labels: ✨ feature

#52 Feature/45 거래 상세 내역 수정 등록 axios 연결
  MoneyDefenseJGS/package-lock.json
  MoneyDefenseJGS/package.json
  MoneyDefenseJGS/public/db/db.json
  MoneyDefenseJGS/src/App.vue
  MoneyDefenseJGS/src/api/transactionApi.js
  MoneyDefenseJGS/src/components/EditableTransactionInformation.vue
  MoneyDefenseJGS/src/components/SaveTransactionButton.vue
  MoneyDefenseJGS/src/components/TransactionStore.vue
  MoneyDefenseJGS/src/components/TransactionSummary.vue
  MoneyDefenseJGS/src/components/TransactionTitle.vue
  MoneyDefenseJGS/src/components/setting/ListItem.vue
  MoneyDefenseJGS/src/components/setting/SettingButton.vue
  MoneyDefenseJGS/src/components/setting/SettingToast.vue
  MoneyDefenseJGS/src/components/setting/SideModal.vue
  MoneyDefenseJGS/src/components/setting/ToggleSwitchTheme.vue
  MoneyDefenseJGS/src/components/setting/UserInfoCard.vue
  MoneyDefenseJGS/src/pages/TransactionCreatePage.vue
  MoneyDefenseJGS/src/pages/layout/AppLayoutPage.vue
  MoneyDefenseJGS/src/pages/setting/SettingsPage.vue
  MoneyDefenseJGS/src/pages/setting/UserEditPage.vue
  MoneyDefenseJGS/src/pages/stores/stores/transaction.ts
  MoneyDefenseJGS/src/stores/profileStore.js
  MoneyDefenseJGS/src/stores/themeStore.js
Labels: ✨ feature, 🐛 bugfix

#59 Feature/3 달력 페이지 구현
  MoneyDefenseJGS/package-lock.json
  MoneyDefenseJGS/package.json
  MoneyDefenseJGS/src/components/CalendarFilter.vue
  MoneyDefenseJGS/src/components/MonthNavigation.vue
  MoneyDefenseJGS/src/main.js
  MoneyDefenseJGS/src/pages/Calendar.vue
  MoneyDefenseJGS/src/router/index.js
Labels: 🎨 design, ✨ feature, 🐛 bugfix

#60 Feature/50 404 페이지 구현하기
  MoneyDefenseJGS/public/db/Dashboard.json
  MoneyDefenseJGS/src/pages/NotFound.vue
  MoneyDefenseJGS/src/router/index.js
Labels: 🎨 design, ✨ feature

#61 Feature/55 realfootervue 구현
  MoneyDefenseJGS/src/components/setting/RealFooter.vue
Labels: 🎨 design, 📄 documentation

#65 Feat: 거래내역 수정과 등록 페이지 anxios 구현, 결제수단 오류 수정, 수입 카테고리 수정
  MoneyDefenseJGS/public/db/db.json
  MoneyDefenseJGS/src/api/transaction.js
  MoneyDefenseJGS/src/api/transactionApi.js
  MoneyDefenseJGS/src/components/EditableTransactionInformation.vue
  MoneyDefenseJGS/src/components/SaveTransactionButton.vue
  MoneyDefenseJGS/src/components/TransactionStore.vue
Labels: ✨ feature, 🐛 bugfix

#66 50 404 페이지 구현하기
  MoneyDefenseJGS/package.json
  MoneyDefenseJGS/public/db/db.json
  MoneyDefenseJGS/src/components/DashBoard/CategoryChart.vue
  MoneyDefenseJGS/src/components/DashBoard/MonthlyChart.vue
  MoneyDefenseJGS/src/components/DashBoard/TotalMoney.vue
Labels: 🎨 design, ✨ feature

#69 Feature/64 homepage cardboard 관련 기능 구현
  MoneyDefenseJGS/src/api/asset.js
  MoneyDefenseJGS/src/api/transactionApi.js
  MoneyDefenseJGS/src/components/cardBoard/AssetTotalCard.vue
  MoneyDefenseJGS/src/components/cardBoard/TransactionCard.vue
  MoneyDefenseJGS/src/components/common/BottomNavBar.vue
  MoneyDefenseJGS/src/components/common/RealHeader.vue
  MoneyDefenseJGS/src/pages/layout/AppLayoutPage.vue
  MoneyDefenseJGS/src/pages/start/HomePage.vue
Labels: 🎨 design, ✨ feature

#71 Feature/18 거래 내역 리스트 구현
  MoneyDefenseJGS/public/db/db.json
  MoneyDefenseJGS/src/api/transactionApi.js
  MoneyDefenseJGS/src/components/common/AddButton.vue
  MoneyDefenseJGS/src/components/transaction/CategoryFilter.vue
  MoneyDefenseJGS/src/components/transaction/TransactionList.vue
  MoneyDefenseJGS/src/components/transaction/TransactionListItem.vue
  MoneyDefenseJGS/src/pages/TransactionPage.vue
  MoneyDefenseJGS/src/pages/layout/AppLayoutPage.vue
Labels: 🎨 design, ✨ feature, 🐛 bugfix

#75 Feature/70 지갑지켜진기스 디자인 통일 작업
  MoneyDefenseJGS/src/App.vue
  MoneyDefenseJGS/src/assets/img/Logo.png
  MoneyDefenseJGS/src/components/DashBoard/CategoryChart.vue
  MoneyDefenseJGS/src/components/DashBoard/MonthlyChart.vue
  MoneyDefenseJGS/src/components/DashBoard/TotalMoney.vue
  MoneyDefenseJGS/src/components/button/EditCardBoardButton.vue
  MoneyDefenseJGS/src/components/common/AmountEditForm.vue
  MoneyDefenseJGS/src/components/common/BaseBox.vue
  MoneyDefenseJGS/src/components/common/BaseButton.vue
  MoneyDefenseJGS/src/components/common/BottomNavBar.vue
  MoneyDefenseJGS/src/components/common/RealHeader.vue
  MoneyDefenseJGS/src/components/common/TabSwitch.vue
  MoneyDefenseJGS/src/components/form/TextInputField.vue
  MoneyDefenseJGS/src/components/setting/ListItem.vue
  MoneyDefenseJGS/src/components/setting/RealFooter.vue
  MoneyDefenseJGS/src/components/setting/SideModal.vue
  MoneyDefenseJGS/src/pages/AssetBudgetTotalPage.vue
  MoneyDefenseJGS/src/pages/BudgetEditPage.vue
  MoneyDefenseJGS/src/pages/layout/AppLayoutPage.vue
  MoneyDefenseJGS/src/pages/report/ReportPage.vue
  MoneyDefenseJGS/src/pages/setting/SettingsPage.vue
  MoneyDefenseJGS/src/pages/setting/UserEditPage.vue
  MoneyDefenseJGS/src/pages/start/OnboardingPage.vue
Labels: 🎨 design, 📄 documentation

#83 Design: ConfirmPopup full screen으로 수정
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/task.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/labels.yml
  MoneyDefenseJGS/src/components/popup/ConfirmPopup.vue
  README.md
Labels: 🎨 design

#85 Docs: readme 수정
  README.md
Labels: 📄 documentation
